### ISSUE TITLE
Auto Z calibration (possible) fix?

### ISSUE THREAD

**Issue by Forrest-O** [0xD34D/ender3-v3-se-klipper-config#16]
So I found this and it may be a possible fix. 
https://github.com/protoloft/klipper_z_calibration/wiki/How-To-Configure-It 
If this fixes the issue, I ask i get notified. I hope this helps. I will get into some form of coding at some point, but as of now, I am not really into any. Also, just a little thing; could you link this? It bypasses the LCD issue.
https://github.com/suchmememanyskill/CYD-Klipper

**Comment by 0xD34D** [comment]
There's already a custom fork of klipper that supports auto z-offset at https://github.com/0xD34D/klipper_ender3_v3_se

I'll update the readme to reflect this.  Thanks!
