### ISSUE TITLE
Filament sensor support?

### ISSUE THREAD

**Issue by pellcorp** [0xD34D/ender3-v3-se-klipper-config#17]
Will a filament sensor connected to the main board work?   Or do I need to connect it to the rpi?

**Comment by 0xD34D** [comment]
Filament sensor works connected to the main board.  There's a connector on there that is marked "Filament".
I also have a config for using it https://github.com/0xD34D/ender3-v3-se-klipper-config/blob/main/filament_sensor.cfg

**Comment by pellcorp** [comment]
ah awesome thanks so much

**Comment by wrobelda** [comment]
@0xD34D  Did you use a standard Crealty detector? It's said to have 3 pins, meanwhile the motherboard has extra 24V fourth pin, but it's safe to ignore it?

**Comment by 0xD34D** [comment]
> @0xD34D  Did you use a standard Crealty detector? It's said to have 3 pins, meanwhile the motherboard has extra 24V fourth pin, but it's safe to ignore it?

I used a generic 3 pin sensor and it was fine to just connect +5V, GND and the signal pin.

**Comment by Haleysoftware** [comment]
The Crealty filament sensor that I just bought came with a 3 to 4 pin extension cable. Not sure when they started including it, but it seems like it might have been around the KE release.
