### ISSUE TITLE
"Section 'filter' is not a valid config section" error

### ISSUE THREAD

**Issue by inigomontoyaik** [0xD34D/ender3-v3-se-klipper-config#25]
tried flashing for the auto z offset, but getting this error. what does it mean an how to fix it?
[klippy (9).log](https://github.com/user-attachments/files/17758560/klippy.9.log)

**Comment by inigomontoyaik** [comment]
nvm i didnt download it correctly lol

**Comment by kevinviana** [comment]
> tried flashing for the auto z offset, but getting this error. what does it mean an how to fix it? [klippy (9).log](https://github.com/user-attachments/files/17758560/klippy.9.log)

how you've fixed it?

**Comment by 503Dev** [comment]
This is the result of using the prtouch.cfg from this repo but not using the custom Klipper. Make sure to download and use the customized Klippe from the repo. If you use Kiauh you can add a custom repo.
