### ISSUE TITLE
Bed mesh fails to generate, move out of range

### ISSUE THREAD

**Issue by shebang79** [0xD34D/ender3-v3-se-klipper-config#3]
I get the follow messages

// probe at 54.000,43.000 is z=2.657500
// probe at 98.250,43.000 is z=2.685000
// probe at 142.500,43.000 is z=2.782500
// probe at 186.750,43.000 is z=2.815000
!! Move out of range: 231.000 43.000 5.000 [0.000]

There might be enough variation between printers that the default is a bit too aggressive.

**Comment by Xarthias** [comment]
Have the same issue, change max mesh values to 206,215.5 and it should work

**Comment by profilelag** [comment]
Just saw this, I added a PR with the change based on your solution, hope they get to it.
