### ISSUE TITLE
Direct serial connection information incorrect

### ISSUE THREAD

**Issue by suchmememanyskill** [0xD34D/ender3-v3-se-klipper-config#9]
Hi, in your config you state the following:

```
# If you prefer a direct serial connection, in "make menuconfig"
# select "Enable extra low-level configuration options" and select
# serial (on USART3 PB11/PB10), which is broken out on the 10 pin IDC
# cable used for the LCD module as follows:
# 3: Tx, 4: Rx, 9: GND, 10: VCC
```

This however, does not work. Using the same pins as the S1 does work: https://github.com/Klipper3d/klipper/blob/master/config/printer-creality-ender3-s1-2021.cfg#L9

**Comment by 0xD34D** [comment]
Addressed here https://github.com/0xD34D/ender3-v3-se-klipper-config/commit/750ad9b11a9aa4b71c69f5b04e6b44985a404ed1
